apiVersion: v1
kind: Service
metadata:
  name: techtrends-service
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - protocol: {{ .Values.service.protocol }}
      port: {{ .Values.service.port }}
      targetPort: 
        {{- if .Values.service.targetPort }}
        {{ .Values.service.targetPort }}
        {{- else }}
        {{ .Values.service.port }}
        {{- end }}
  selector:
    app: techtrends
  type: {{ .Values.service.type }}
