apiVersion: v1
name: techtrends
keywords:
  - techtrends
version: 1.0.0
maintainers:
  - name: Nikita Shrestha
    email: nikshres522@gmail.com
description: A Helm chart for Kubernetes to deploy techtrends
