namespace: staging
replicaCount: 3
image:
  username: nikistha
  repository: techtrends
  tag: latest
  pullPolicy: Always
service:
  port: 5111
resources:
  requests:
    memory: "90Mi"
    cpu: "300m"
  limits:
    memory: "128Mi"
    cpu: "500m"
